### ISSUE TITLE
Sageattention in flux

### ISSUE THREAD

**Issue by todochenxi** [thu-ml/SageAttention#32]
Hello, when I use SageAttention in Flux, it throws an error because the sequence_len of the clip is less than 128. Do you plan to support Flux ~

**Comment by jt-zhang** [comment]
SageAttention works well in flux, and we think the sequence_len in flux is about 5K for images with 1K resolution.
Could you please provide more information about the sequence_len you met?

**Comment by todochenxi** [comment]
```python
import torch
from diffusers import FluxPipeline
from sageattention import sageattn
import torch.nn.functional as F
F.scaled_dot_product_attention = sageattn

import os
# os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'max_split_size_mb:72'
pipe = FluxPipeline.from_pretrained("black-forest-labs/FLUX.1-dev", torch_dtype=torch.bfloat16)
# pipe.enable_model_cpu_offload() #save some VRAM by offloading the model to CPU. Remove this if you have enough GPU power
pipe.enable_sequential_cpu_offload()
prompt = "A cat holding a sign that says hello world"
image = pipe(
    prompt,
    height=1024,
    width=1024,
    guidance_scale=3.5,
    num_inference_steps=50,
    max_sequence_length=512,
    generator=torch.Generator("cpu").manual_seed(0)
).images[0]
image.save("flux-dev.png")
```
Error
```python
Traceback (most recent call last):
  File "/data3/ml/flux/demo.py", line 13, in <module>
    image = pipe(
  File "/data3/anaconda3/envs/photomaker/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/data3/anaconda3/envs/photomaker/lib/python3.10/site-packages/diffusers/pipelines/flux/pipeline_flux.py", line 635, in __call__
    ) = self.encode_prompt(
  File "/data3/anaconda3/envs/photomaker/lib/python3.10/site-packages/diffusers/pipelines/flux/pipeline_flux.py", line 344, in encode_prompt
    pooled_prompt_embeds = self._get_clip_prompt_embeds(
  File "/data3/anaconda3/envs/photomaker/lib/python3.10/site-packages/diffusers/pipelines/flux/pipeline_flux.py", line 276, in _get_clip_prompt_embeds
    prompt_embeds = self.text_encoder(text_input_ids.to(device), output_hidden_states=False)
  File "/data3/anaconda3/envs/photomaker/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data3/anaconda3/envs/photomaker/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data3/anaconda3/envs/photomaker/lib/python3.10/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/data3/anaconda3/envs/photomaker/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 1050, in forward
    return self.text_model(
  File "/data3/anaconda3/envs/photomaker/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data3/anaconda3/envs/photomaker/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data3/anaconda3/envs/photomaker/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 954, in forward
    encoder_outputs = self.encoder(
  File "/data3/anaconda3/envs/photomaker/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data3/anaconda3/envs/photomaker/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data3/anaconda3/envs/photomaker/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 877, in forward
    layer_outputs = encoder_layer(
  File "/data3/anaconda3/envs/photomaker/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data3/anaconda3/envs/photomaker/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data3/anaconda3/envs/photomaker/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 608, in forward
    hidden_states, attn_weights = self.self_attn(
  File "/data3/anaconda3/envs/photomaker/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data3/anaconda3/envs/photomaker/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data3/anaconda3/envs/photomaker/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 540, in forward
    attn_output = torch.nn.functional.scaled_dot_product_attention(
  File "/data3/anaconda3/envs/photomaker/lib/python3.10/site-packages/sageattention/core.py", line 24, in sageattn
    assert q.size(-2)>=128, "seq_len should be not less than 128."
AssertionError: seq_len should be not less than 128.
```
Thank you for your reply. The code and error message above are from my running environment.

**Comment by jt-zhang** [comment]
Using `F.scaled_dot_product_attention = sageattn` does not always work. You should replace the `model.transformer_blocks.attn` and `model.single_transformer_blocks` with `sageattn` in flux. We will release an example about flux soon.
