### ISSUE TITLE
1.0.5 errors with bf16 CogVideoX: AssertionError: First input (fp16) and second input (bf16) must have the same dtype!

### ISSUE THREAD

**Issue by kijai** [thu-ml/SageAttention#44]
Hey,

Having this issue after updating to 1.0.5 (or 1.0.4) from 1.0.3 when running CogVideoX in bf16, with fp16 it works fine too.

```
!!! Exception during processing !!! at 36:15:
    K_ptrs = K + (off_z * stride_kz + (off_h // num_kv_groups) * stride_kh) + offs_n[None, :] * stride_kn + offs_k[:, None]
    K_scale_ptr = K_scale + k_scale_offset
    V_ptrs = V + (off_z * stride_vz + (off_h // num_kv_groups) * stride_vh) + offs_n[:, None] * stride_vn + offs_k[None, :]
    O_block_ptr = Out + (off_z * stride_oz + off_h * stride_oh) + offs_m[:, None] * stride_on + offs_k[None, :]

    m_i = tl.zeros([BLOCK_M], dtype=tl.float32) - float("inf")
    l_i = tl.zeros([BLOCK_M], dtype=tl.float32) + 1.0
    acc = tl.zeros([BLOCK_M, HEAD_DIM], dtype=tl.float32)

    q = tl.load(Q_ptrs, mask = offs_m[:, None] < qo_len)
    q_scale = tl.load(Q_scale_ptr)
    acc, l_i = _attn_fwd_inner(acc, l_i, m_i, q, q_scale, kv_len, K_ptrs, K_scale_ptr, V_ptrs, stride_kn, stride_vn,
               ^
Traceback (most recent call last):
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\code_generator.py", line 1116, in visit_Call
    return fn(*args, **extra_kwargs, **kws)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\language\core.py", line 35, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\language\core.py", line 1534, in dot
    return semantic.dot(input, other, acc, input_precision, max_num_imprecise_acc, out_dtype, _builder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\language\semantic.py", line 1355, in dot
    assert_dtypes_valid(lhs.dtype, rhs.dtype, builder.options)
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\language\semantic.py", line 1352, in assert_dtypes_valid
    assert lhs_dtype == rhs_dtype, f"First input ({lhs_dtype}) and second input ({rhs_dtype}) must have the same dtype!"
           ^^^^^^^^^^^^^^^^^^^^^^
AssertionError: First input (fp16) and second input (bf16) must have the same dtype!

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\code_generator.py", line 1074, in call_JitFunction
    generator.visit(fn.parse())
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\code_generator.py", line 1204, in visit
    ret = super().visit(node)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jukka\AppData\Local\Programs\Python\Python312\Lib\ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\code_generator.py", line 359, in visit_Module
    ast.NodeVisitor.generic_visit(self, node)
  File "C:\Users\Jukka\AppData\Local\Programs\Python\Python312\Lib\ast.py", line 415, in generic_visit
    self.visit(item)
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\code_generator.py", line 1204, in visit
    ret = super().visit(node)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jukka\AppData\Local\Programs\Python\Python312\Lib\ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\code_generator.py", line 443, in visit_FunctionDef
    self.visit_compound_statement(node.body)
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\code_generator.py", line 351, in visit_compound_statement
    self.visit(stmt)
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\code_generator.py", line 1204, in visit
    ret = super().visit(node)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jukka\AppData\Local\Programs\Python\Python312\Lib\ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\code_generator.py", line 964, in visit_For
    self.visit_compound_statement(node.body)
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\code_generator.py", line 351, in visit_compound_statement
    self.visit(stmt)
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\code_generator.py", line 1204, in visit
    ret = super().visit(node)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jukka\AppData\Local\Programs\Python\Python312\Lib\ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\code_generator.py", line 516, in visit_AugAssign
    self.visit(assign)
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\code_generator.py", line 1204, in visit
    ret = super().visit(node)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jukka\AppData\Local\Programs\Python\Python312\Lib\ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\code_generator.py", line 496, in visit_Assign
    values = self.visit(node.value)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\code_generator.py", line 1204, in visit
    ret = super().visit(node)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jukka\AppData\Local\Programs\Python\Python312\Lib\ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\code_generator.py", line 545, in visit_BinOp
    rhs = self.visit(node.right)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\code_generator.py", line 1204, in visit
    ret = super().visit(node)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jukka\AppData\Local\Programs\Python\Python312\Lib\ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\code_generator.py", line 1124, in visit_Call
    raise CompilationError(self.jit_fn.src, node, None) from e
triton.compiler.errors.CompilationError: at 27:15:
        p = tl.math.exp2(qk)
        l_ij = tl.sum(p, 1)

        alpha = tl.math.exp2(m_i - m_ij)
        l_i = l_i * alpha + l_ij

        acc = acc * alpha[:, None]

        v = tl.load(V_ptrs, mask = offs_n[:, None] < (kv_len - start_n))
        p = p.to(tl.float16)

        acc += tl.dot(p, v, out_dtype=tl.float16)
               ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "N:\AI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "N:\AI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 686, in process
    latents = model["pipe"](
              ^^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\pipeline_cogvideox.py", line 750, in __call__
    noise_pred = self.transformer(
                 ^^^^^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\custom_cogvideox_transformer_3d.py", line 685, in forward
    hidden_states, encoder_hidden_states = block(
                                           ^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\custom_cogvideox_transformer_3d.py", line 282, in forward
    attn_hidden_states, attn_encoder_hidden_states = self.attn1(
                                                     ^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\diffusers\models\attention_processor.py", line 495, in forward
    return self.processor(
           ^^^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\custom_cogvideox_transformer_3d.py", line 129, in __call__
    hidden_states = sageattn_func(query, key, value, attn_mask=attention_mask, dropout_p=0.0,is_causal=False)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\torch\_dynamo\eval_frame.py", line 632, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\custom_cogvideox_transformer_3d.py", line 51, in sageattn_func
    return sageattn(query, key, value, attn_mask=attn_mask, dropout_p=dropout_p,is_causal=is_causal)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\sageattention\core.py", line 106, in sageattn
    o = attn_true(q_int8, k_int8, v, q_scale, k_scale, tensor_layout=tensor_layout, output_dtype=dtype)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\sageattention\attn_qk_int8_per_block.py", line 113, in forward
    _attn_fwd[grid](
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\runtime\jit.py", line 345, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\runtime\jit.py", line 662, in run
    kernel = self.compile(
             ^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\compiler.py", line 280, in compile
    module = src.make_ir(options, codegen_fns, context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\compiler.py", line 113, in make_ir
    return ast_to_ttir(self.fn, self, context=context, options=options, codegen_fns=codegen_fns)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\code_generator.py", line 1297, in ast_to_ttir
    generator.visit(fn.parse())
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\code_generator.py", line 1204, in visit
    ret = super().visit(node)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jukka\AppData\Local\Programs\Python\Python312\Lib\ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\code_generator.py", line 359, in visit_Module
    ast.NodeVisitor.generic_visit(self, node)
  File "C:\Users\Jukka\AppData\Local\Programs\Python\Python312\Lib\ast.py", line 415, in generic_visit
    self.visit(item)
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\code_generator.py", line 1204, in visit
    ret = super().visit(node)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jukka\AppData\Local\Programs\Python\Python312\Lib\ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\code_generator.py", line 443, in visit_FunctionDef
    self.visit_compound_statement(node.body)
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\code_generator.py", line 351, in visit_compound_statement
    self.visit(stmt)
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\code_generator.py", line 1204, in visit
    ret = super().visit(node)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jukka\AppData\Local\Programs\Python\Python312\Lib\ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\code_generator.py", line 496, in visit_Assign
    values = self.visit(node.value)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\code_generator.py", line 1204, in visit
    ret = super().visit(node)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jukka\AppData\Local\Programs\Python\Python312\Lib\ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\code_generator.py", line 1109, in visit_Call
    return self.call_JitFunction(fn, args, kws)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "N:\AI\ComfyUI\venv\Lib\site-packages\triton\compiler\code_generator.py", line 1077, in call_JitFunction
    raise CompilationError(self.jit_fn.src, self.cur_node, None) from e
triton.compiler.errors.CompilationError: at 36:15:
    K_ptrs = K + (off_z * stride_kz + (off_h // num_kv_groups) * stride_kh) + offs_n[None, :] * stride_kn + offs_k[:, None]
    K_scale_ptr = K_scale + k_scale_offset
    V_ptrs = V + (off_z * stride_vz + (off_h // num_kv_groups) * stride_vh) + offs_n[:, None] * stride_vn + offs_k[None, :]
    O_block_ptr = Out + (off_z * stride_oz + off_h * stride_oh) + offs_m[:, None] * stride_on + offs_k[None, :]

    m_i = tl.zeros([BLOCK_M], dtype=tl.float32) - float("inf")
    l_i = tl.zeros([BLOCK_M], dtype=tl.float32) + 1.0
    acc = tl.zeros([BLOCK_M, HEAD_DIM], dtype=tl.float32)

    q = tl.load(Q_ptrs, mask = offs_m[:, None] < qo_len)
    q_scale = tl.load(Q_scale_ptr)
    acc, l_i = _attn_fwd_inner(acc, l_i, m_i, q, q_scale, kv_len, K_ptrs, K_scale_ptr, V_ptrs, stride_kn, stride_vn,
```

**Comment by jason-huang03** [comment]
hello, can you provide the model and script of running cogvideo so that we can debug?

**Comment by jason-huang03** [comment]
We test have test bf16 input to the `sageattention` function and it works fine. So we suppose that inside the model there is some type mismatch so we need your running script to debug.

**Comment by jt-zhang** [comment]
Could you please provide the input `shape and dtype` of `q, k, v`? @kijai

**Comment by jason-huang03** [comment]
The logic of our code now is that we check the dtype of `q` and then assume `k` `v` is of the same dtype. We suspect the problem is that `q` is of dtype `fp16` and `v` is of dtype `bf16`.

**Comment by kijai** [comment]
> Could you please provide the input `shape and dtype` of `q, k, v`? @kijai

Yes of course, I should've done that initially, for example when doing image2video at 720x480x49:
```
query shape:  torch.Size([2, 48, 17776, 64]) dtype:  torch.float32
key shape:  torch.Size([2, 48, 17776, 64]) dtype:  torch.float32
value shape:  torch.Size([2, 48, 17776, 64]) dtype:  torch.bfloat16
```

This has been fine with 1.0.3 and I can't figure out what changed. It's also not only on my system as others have reported same issue.

This is running in ComfyUI using my wrapper nodes: https://github.com/kijai/ComfyUI-CogVideoXWrapper

**Comment by jason-huang03** [comment]
Oh I see, our wrapper now does not perform rigurous check of data type at 1.0.5. We assume that input type are either of all `fp16` or `bf16`, as is the case of huggingface transformers of diffusers. I wonder in the example you provided what output type do you expect?

**Comment by jason-huang03** [comment]
We check `torch.nn.functioal.scaled_dot_product_attention`, it restrict input `q`, `k`, `v` to be of the same data type, but allows input to have `torch.float32` data type. The output type is the same as the input type. Do you think this is a reasonble and easy-to-use interface?

**Comment by jason-huang03** [comment]
We have added device and dtype check. Now the requirement of input should align with `torch.nn.functional.scale_dot_product_attention`. We will upload a new version to pip soon.

**Comment by kijai** [comment]
Thank you!
