### ISSUE TITLE
sageattn 2.0编译成功，运行报错, triton版本可以正常运行

### ISSUE THREAD

**Issue by DefTruth** [thu-ml/SageAttention#49]
```bash
Traceback (most recent call last):
  File "/workspace/dev/openllm/SageAttention/example/sageattn_cogvideo.py", line 19, in <module>
    video = pipe(
  File "/root/anaconda3/envs/trtllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/trtllm/lib/python3.10/site-packages/diffusers/pipelines/cogvideo/pipeline_cogvideox.py", line 710, in __call__
    noise_pred = self.transformer(
  File "/root/anaconda3/envs/trtllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/trtllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/trtllm/lib/python3.10/site-packages/diffusers/models/transformers/cogvideox_transformer_3d.py", line 503, in forward
    hidden_states, encoder_hidden_states = block(
  File "/root/anaconda3/envs/trtllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/trtllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/trtllm/lib/python3.10/site-packages/diffusers/models/transformers/cogvideox_transformer_3d.py", line 132, in forward
    attn_hidden_states, attn_encoder_hidden_states = self.attn1(
  File "/root/anaconda3/envs/trtllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/trtllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/trtllm/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 530, in forward
    return self.processor(
  File "/root/anaconda3/envs/trtllm/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 2301, in __call__
    hidden_states = hidden_states.transpose(1, 2).reshape(batch_size, -1, attn.heads * head_dim)
RuntimeError: CUDA error: unspecified launch failure
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
- sageattn 2.0 build from source
- pytorch 2.5
- CUDA 12.3, 手动relax CUDA版本到12.3编译sm_89(L20)，编译成功，测试cogvideox报错。

triton版本可以正常运行。

**Comment by jason-huang03** [comment]
You can use fp16 PV or update cuda version.
