### ISSUE TITLE
End To End performance example and problem with batch size

### ISSUE THREAD

**Issue by l1cacheDell** [thu-ml/SageAttention#72]
Hello, I'm doing roughly e2e performance metric with sage attn 1 on A100, I haven't seen any e2e benchmark code in the repository so I just roughly did some test like this:

```python
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch
import time
from sageattention import sageattn
import torch.nn.functional as F

model_name = "meta-llama/Llama-2-7b-chat-hf" 
input_texts = ["What's the meaning of life?", "What's the meaning of school?"]

tokenizer = AutoTokenizer.from_pretrained(model_name)
F.scaled_dot_product_attention = sageattn
model = AutoModelForCausalLM.from_pretrained(model_name, device_map="auto", torch_dtype=torch.float16)
tokenizer.pad_token = tokenizer.eos_token

inputs = tokenizer(input_texts, return_tensors="pt").to("cuda")

start = time.monotonic()
for i in range(5):
    outputs = model.generate(**inputs, max_length=100, temperature=0.01, do_sample=True)

end = time.monotonic()
print(f"sage attn inference took: {end - start} s")

generated_text = tokenizer.batch_decode(outputs, skip_special_tokens=True)
print(generated_text)
```

It went smoothly and I have seen speed up compared to `FA2`, but when I tried to increase `batch_size`, like this:

```python
input_texts = ["What's the meaning of life?", "What's the meaning of school?", "What's the meaning of life?", "What's the meaning of school?"]
```

Then the program failed and logs from the terminal:

```
miniconda3/envs/dyz_sageattn/lib/python3.11/site-packages/sageattention-2.0.0-py3.11-linux-x86_64.egg/sageattention/core.py:480: UserWarning: pv_accum_dtype is fp32, smooth_v will be ignored.
  warnings.warn(f"pv_accum_dtype is {pv_accum_dtype}, smooth_v will be ignored.")
/opt/conda/conda-bld/pytorch_1729647429097/work/aten/src/ATen/native/cuda/TensorCompare.cu:110: _assert_async_cuda_kernel: block: [0,0,0], thread: [0,0,0] Assertion `probability tensor contains either `inf`, `nan` or element < 0` failed.
Traceback (most recent call last):
  File "/workspace/env_run/output/sage_attn_e2e/inference_llama.py", line 100, in <module>
    latency_sageattn = sage_attn_inference()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/env_run/output/sage_attn_e2e/inference_llama.py", line 83, in sage_attn_inference
    outputs = model.generate(**inputs, max_length=100, temperature=0.01, do_sample=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/envs/dyz_sageattn/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/envs/dyz_sageattn/lib/python3.11/site-packages/transformers/generation/utils.py", line 2252, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "miniconda3/envs/dyz_sageattn/lib/python3.11/site-packages/transformers/generation/utils.py", line 3240, in _sample
    while self._has_unfinished_sequences(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/envs/dyz_sageattn/lib/python3.11/site-packages/transformers/generation/utils.py", line 2450, in _has_unfinished_sequences
    elif this_peer_finished:
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

---

So if I may ask:

+ Could you please provide the e2e performance code? Or I will continue with my code (Maybe it will get metric results different from what is claimed in paper)
+ Do you know what's wrong when incresing `batch_size` that triggered this error?

**Comment by jason-huang03** [comment]
Hi, currently sage attention only support api same as torch.nn.functional.scaled_dot_product_attention without attention mask argument. So theoretically sage attention cannot do batch generation on LLMs.

**Comment by jason-huang03** [comment]
e2e code will be available soon.

**Comment by l1cacheDell** [comment]
Thank you for your prompt reply :)
