### ISSUE TITLE
Long sequence error

### ISSUE THREAD

**Issue by l1cacheDell** [thu-ml/SageAttention#75]
Hello, I was trying to use `sageattn` API to test a long seq_len attention seetings like this:

```python
target_len = 128000
for seq_len in {target_len}:
    flops = 4 * head * batch * headdim * seq_len * seq_len // (2 if is_causal else 1)
    # flash attn
    q = torch.randn(batch, seq_len, head, headdim).half().cuda()
    k = torch.randn(batch, seq_len, head, headdim).half().cuda()
    v = torch.randn(batch, seq_len, head, headdim).half().cuda()

    # sage attn
    sm_scale = 1 / (headdim ** 0.5)
    o2 = None
    for i in range(5): o2 = sageattn(q, k, v, is_causal=is_causal, tensor_layout='NHD', sm_scale=sm_scale)
    
    torch.cuda.synchronize()
    _, time2 = benchmark_forward(sageattn, q, k, v, is_causal=is_causal, sm_scale=sm_scale, 
                                repeats=100, verbose=False, desc='Triton')
    sa_flops = flops/time2.mean*1e-12
    print(f"sa  total: {time2.mean * 100}")
    print(f"sa  time: {time2.mean}")
    
    print(f'seq_len: {seq_len}, SA  flops: {sa_flops}')
```

I want to test a 128K seq_len and the error shows:

```
batch: 2, head: 28, headdim: 128
is_causal: False
Traceback (most recent call last):
  File "sage_attn_e2e/kernel_any_shape.py", line 47, in <module>
    _, time2 = benchmark_forward(sageattn, q, k, v, is_causal=is_causal, sm_scale=sm_scale, 
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flash_attn/utils/benchmark.py", line 24, in benchmark_forward
    m = t.timeit(repeats)
        ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/utils/benchmark/utils/timer.py", line 274, in timeit
    self._timeit(number=max(int(number // 100), 2))
  File "/usr/local/lib/python3.11/dist-packages/torch/utils/benchmark/utils/timer.py", line 264, in _timeit
    return max(self._timer.timeit(number), 1e-9)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/timeit.py", line 178, in timeit
    timing = self.inner(it, self.timer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<timeit-src>", line 6, in inner
  File "/usr/local/lib/python3.11/dist-packages/flash_attn/utils/benchmark.py", line 17, in amp_wrapper
    fn(*inputs, **kwinputs)
  File "SageAttention/sageattention/core.py", line 120, in sageattn
    return sageattn_qk_int8_pv_fp16_cuda(q, k, v, tensor_layout=tensor_layout, is_causal=is_causal, sm_scale=sm_scale, return_lse=return_lse, pv_accum_dtype="fp32")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "SageAttention/sageattention/core.py", line 467, in sageattn_qk_int8_pv_fp16_cuda
    km = k.mean(dim=seq_dim, keepdim=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: invalid configuration argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

It is weired that, normal `sageattn` func may hold 128K seq_len, that is the 5 times for loop warm up. (Because the sageattn hasn't thrown any error.)

While the `benchmark_forward()` function cannot do well with 128K seq_len.

So: have you ever tested 128K length with `benchmark_forward(sageattn, q, k, v, ...)`? Or maybe my settings were wrong.

**Comment by jason-huang03** [comment]
If you use 128k sequence length with sage attention in real model, is the result correct?

**Comment by l1cacheDell** [comment]
Thank you for your reply, actually when I was testing our sageattn kernel in long-sequence scenarios, we have observed the accuracy diff, along with the tokens increasing, we have the screenshot here to demonstrate:

![image](https://github.com/user-attachments/assets/d7d9fa90-0cae-4f28-b5fe-1696c3b36271)

We use:

```python
print(o2 - o1)
```

to observe the diff, where `o1` stands for FA2 results, and `o2` stands for SA results. (output from attention). As you can see there are some diff with tokens increasing.

As for real output words, we have observed that the results are **readable**.

---

So based on your response, may I have following conclusion:

+ Sage Attn may work fine in long-context scenarios, though there will be some evitable precision loss.
+ `sageattn` kernel actually works for 128K, but is just not compatible with `benchmark_forward` function, and I should find alternative way to profile sageattn for 128K.

**Comment by jason-huang03** [comment]
What GPU do you test on? SageAttention will route the input to different kernels based on GPU architecture. Bythe way we have just release 2.0.1 which should be more accurate with negligible overhead.

**Comment by l1cacheDell** [comment]
A100.

**Comment by jason-huang03** [comment]
Now on sm80 the result should be extremely accurate, giving to 1.2-1.3x speedup. Would you like to verify again?

**Comment by l1cacheDell** [comment]
> What GPU do you test on? SageAttention will route the input to different kernels based on GPU architecture. Bythe way we have just release 2.0.1 which should be more accurate with negligible overhead.

Hello, I have tested release 2.0.1, and I have found that the overhead may not be negligible, compared to my previous experiments. 

I don't know if my code to profile sageattn and flash attn was correct, so feel free to comment:

```python
import torch
from flash_attn.utils.benchmark import benchmark_forward
from flash_attn import flash_attn_func
from sageattention import sageattn
from rich import print
import torch.nn.functional as F

import argparse

parser = argparse.ArgumentParser(description='Benchmark Baseline')
parser.add_argument('--batch_size', type=int, default=4, help='Batch size')
parser.add_argument('--num_heads', type=int, default=32, help='Number of heads')
parser.add_argument('--head_dim', type=int, default=128, help='Head dimension')
parser.add_argument('--seq_len', type=int, default=4096, help="Sequence length")
args = parser.parse_args()

head = args.num_heads
batch = args.batch_size
headdim = args.head_dim
target_len = args.seq_len

print(f"batch: {batch}, head: {head}, headdim: {headdim}")

def precision_diff(quant_o: torch.Tensor, fa2_o: torch.Tensor):
    x, xx = quant_o.float(), fa2_o.float() 
    sim = F.cosine_similarity(x.reshape(1, -1), xx.reshape(1, -1)).item()
    l1 =   ( (x - xx).abs().sum() / xx.abs().sum() ).item()
    return sim, l1

is_causal = False
print(f"is_causal: {is_causal}")
_repeat = 100
for seq_len in {target_len}:
    flops = 4 * head * batch * headdim * seq_len * seq_len // (2 if is_causal else 1)
    # flash attn
    q = torch.randn(batch, seq_len, head, headdim).half().cuda()
    k = torch.randn(batch, seq_len, head, headdim).half().cuda()
    v = torch.randn(batch, seq_len, head, headdim).half().cuda()
    o = None
    for i in range(5): o = flash_attn_func(q, k, v, causal=is_causal)
    torch.cuda.synchronize()
    _, time1 = benchmark_forward(flash_attn_func, q, k, v, causal=is_causal, repeats=_repeat, verbose=False, desc='Triton')
    fa2_flops = flops/time1.mean*1e-12

    print("=========== Time Eval ===========")
    print(f"fa2 total: {time1.mean * _repeat}")
    print(f"fa2 time: {time1.mean}")
    
    # sage attn
    sm_scale = 1 / (headdim ** 0.5)
    o2 = None
    for i in range(5): o2 = sageattn(q, k, v, is_causal=is_causal, tensor_layout='NHD', sm_scale=sm_scale)
    
    torch.cuda.synchronize()
    _, time2 = benchmark_forward(sageattn, q, k, v, is_causal=is_causal, tensor_layout='NHD', sm_scale=sm_scale, 
                                repeats=_repeat, verbose=False, desc='Triton')
    sa_flops = flops/time2.mean*1e-12
    print(f"sa  total: {time2.mean * _repeat}")
    print(f"sa  time: {time2.mean}")

    print("=========== ACCURACY ===========")
    sim, l1 = precision_diff(o2, o)
    print("cos sim: ", sim)
    print("L1 diff", l1)
    print("=========== FLOPS ===========")
    print(f"seq_len: {seq_len}, FA2 flops: {fa2_flops}")
    print(f'seq_len: {seq_len}, SA  flops: {sa_flops}')
    print(f"The speed up is: {sa_flops / fa2_flops} x")

print("\n\n======================\n\n")

is_causal = True
print(f"is_causal: {is_causal}")
for seq_len in {target_len}:
    flops = 4 * head * batch * headdim * seq_len * seq_len // (2 if is_causal else 1)
    # flash attn
    q = torch.randn(batch, seq_len, head, headdim).half().cuda()
    k = torch.randn(batch, seq_len, head, headdim).half().cuda()
    v = torch.randn(batch, seq_len, head, headdim).half().cuda()
    o = None
    for i in range(5): o = flash_attn_func(q, k, v, causal=is_causal)
    torch.cuda.synchronize()
    _, time1 = benchmark_forward(flash_attn_func, q, k, v, causal=is_causal, repeats=_repeat, verbose=False, desc='Triton')
    fa2_flops = flops/time1.mean*1e-12
    print("=========== Time Eval ===========")
    print(f"fa2 total: {time1.mean * _repeat}")
    print(f"fa2 time: {time1.mean}")
    
    # sage attn
    o2 = None
    sm_scale = 1 / (headdim ** 0.5)
    for i in range(5): o2 = sageattn(q, k, v, is_causal=is_causal, tensor_layout='NHD', sm_scale=sm_scale)
    
    torch.cuda.synchronize()
    _, time2 = benchmark_forward(sageattn, q, k, v, is_causal=is_causal, sm_scale=sm_scale, tensor_layout='NHD', 
                                repeats=_repeat, verbose=False, desc='Triton')
    sa_flops = flops/time2.mean*1e-12
    print(f"sa total: {time2.mean * _repeat}")
    print(f"sa  time: {time2.mean}")
    
    print("=========== ACCURACY ===========")
    sim, l1 = precision_diff(o2, o)
    print("cos sim: ", sim)
    print("L1 diff", l1)
    print("=========== FLOPS ===========")
    print(f"seq_len: {seq_len}, FA2 flops: {fa2_flops}")
    print(f'seq_len: {seq_len}, SA  flops: {sa_flops}')
    print(f"The speed up is: {sa_flops / fa2_flops} x")
```

The result is: 

```
batch: 4, head: 28, headdim: 128
is_causal: False
=========== Time Eval ===========
fa2 total: 0.5182408196851611
fa2 time: 0.005182408196851611
sa  total: 0.5506552299484611
sa  time: 0.00550655229948461
=========== ACCURACY ===========
cos sim:  0.9999371767044067
L1 diff 0.011128997430205345
=========== FLOPS ===========
seq_len: 4250, FA2 flops: 199.8638394847494
seq_len: 4250, SA  flops: 188.09882185209503
The speed up is: 0.9411348362816171 x


======================


is_causal: True
=========== Time Eval ===========
fa2 total: 0.28078115452080965
fa2 time: 0.0028078115452080965
sa total: 0.3300398541614413
sa  time: 0.0033003985416144134
=========== ACCURACY ===========
cos sim:  0.9999505281448364
L1 diff 0.010696387849748135
=========== FLOPS ===========
seq_len: 4250, FA2 flops: 184.4454272167392
seq_len: 4250, SA  flops: 156.91680670379625
The speed up is: 0.8507492382524916 x
```

And command line is: `python3.11 kernel_any_shape.py --num_heads 28 --head_dim 128 --seq_len 4250`.

The speed up does not meet the expectation. Please tell me if my settings were wrong.

**Comment by jason-huang03** [comment]
Hi, can you `cd` into the `bench` directory and measure the kernel speed of SageAttention? You can use the following command:
```bash
python bench_qk_int8_pv_fp16_cuda.py --quant_gran per_warp --pv_accum_dtype fp32
python bench_qk_int8_pv_fp16_cuda.py --quant_gran per_thread --pv_accum_dtype fp32
```
It is possible that when the sequence is not long, the quantization overhead (quantize and smooth $Q, K$) is not that small compared to the execution time of the kernel. I attach the result on my machine of two most accurate kernels:

```bash
======================
quant_gran: per_warp
CUDA QK Int8 PV FP16
batch: 4, head: 32, headdim: 128, pv_accum_dtype: fp32
is_causal: False
1024 flops:107.38037765743229
2048 flops:198.00941608333105
4096 flops:227.8635065128626
8192 flops:248.85486678261069
16384 flops:252.60755984945217
32768 flops:253.3359054813613
is_causal: True
1024 flops:165.66139366666235
2048 flops:166.39753758274347
4096 flops:187.62353716845652
8192 flops:230.85919831535088
16384 flops:246.09228011290756
32768 flops:249.6430262359967
======================
quant_gran: per_thread
CUDA QK Int8 PV FP16
batch: 4, head: 32, headdim: 128, pv_accum_dtype: fp32
is_causal: False
1024 flops:174.26518153025646
2048 flops:193.98338797638644
4096 flops:232.660385892122
8192 flops:243.993694468198
16384 flops:245.70000799392528
32768 flops:246.37138815848647
is_causal: True
1024 flops:159.89502857737088
2048 flops:161.94829187776216
4096 flops:197.54566637274743
8192 flops:230.96769511532378
16384 flops:239.81764793909326
32768 flops:243.41018063278935
```

I measure the result on A100-SXM4-80G.

**Comment by jason-huang03** [comment]
You can reach me through my email and add my wechat to discuss the detail.

**Comment by l1cacheDell** [comment]
> Hi, can you `cd` into the `bench` directory and measure the kernel speed of SageAttention? You can use the following command:
> 
> ```shell
> python bench_qk_int8_pv_fp16_cuda.py --quant_gran per_warp --pv_accum_dtype fp32
> python bench_qk_int8_pv_fp16_cuda.py --quant_gran per_thread --pv_accum_dtype fp32
> ```
> 
> It is possible that when the sequence is not long, the quantization overhead (quantize and smooth Q , K ) is not that small compared to the execution time of the kernel. I attach the result on my machine of two most accurate kernels:
> 
> ```shell
> ======================
> quant_gran: per_warp
> CUDA QK Int8 PV FP16
> batch: 4, head: 32, headdim: 128, pv_accum_dtype: fp32
> is_causal: False
> 1024 flops:107.38037765743229
> 2048 flops:198.00941608333105
> 4096 flops:227.8635065128626
> 8192 flops:248.85486678261069
> 16384 flops:252.60755984945217
> 32768 flops:253.3359054813613
> is_causal: True
> 1024 flops:165.66139366666235
> 2048 flops:166.39753758274347
> 4096 flops:187.62353716845652
> 8192 flops:230.85919831535088
> 16384 flops:246.09228011290756
> 32768 flops:249.6430262359967
> ======================
> quant_gran: per_thread
> CUDA QK Int8 PV FP16
> batch: 4, head: 32, headdim: 128, pv_accum_dtype: fp32
> is_causal: False
> 1024 flops:174.26518153025646
> 2048 flops:193.98338797638644
> 4096 flops:232.660385892122
> 8192 flops:243.993694468198
> 16384 flops:245.70000799392528
> 32768 flops:246.37138815848647
> is_causal: True
> 1024 flops:159.89502857737088
> 2048 flops:161.94829187776216
> 4096 flops:197.54566637274743
> 8192 flops:230.96769511532378
> 16384 flops:239.81764793909326
> 32768 flops:243.41018063278935
> ```
> 
> I measure the result on A100-SXM4-80G.

Yes I can reproduce that.

I will get in touch with you, thank you for your patience.
